services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:5004
    networks:
      - job_portal_net

  chatbot_service:
    build: ./backend/chatbot_service
    ports:
      - "5004:5004"
    environment:
      - FLASK_ENV=development
    networks:
      - job_portal_net

  # ... other services ...

networks:
  job_portal_net:
    driver: bridge